import { z } from "zod";

export type ImageClassification = "ai-generated" | "authentic" | "uncertain";

export interface ImageDebunkResult {
  classification: ImageClassification;
  /** Certainty of the classification 0–100 (distance from maximum ambiguity) */
  confidence: number;
  /** 0 = safe, 100 = definitely fake */
  riskScore: number;
  safe: boolean;
  summary: string;
  flags: string[];
  explanation: string;
  source: "sightengine";
  modelLabel?: string;
}

export const SAFE_RISK_THRESHOLD = 50;

export const DANGEROUS_IMAGE_CLASSIFICATIONS = new Set<ImageClassification>([
  "ai-generated",
]);

export const ACCEPTED_IMAGE_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/gif",
] as const;

export const MAX_IMAGE_BYTES = 4 * 1024 * 1024;

export function isAcceptedMimeType(mime: string): boolean {
  return (ACCEPTED_IMAGE_MIME_TYPES as readonly string[]).includes(mime);
}

// SightEngine genai model response schema.
// Only the `type.ai_generated` score (0–1) is used for detection.
export const SightengineRawResponseSchema = z.object({
  status: z.literal("success"),
  request: z.object({
    id: z.string(),
    timestamp: z.number(),
    operations: z.number(),
  }),
  type: z.object({
    ai_generated: z.number().min(0).max(1),
  }),
  media: z.object({
    id: z.string(),
    uri: z.string(),
  }),
});

export type SightengineRawResponse = z.infer<
  typeof SightengineRawResponseSchema
>;

export function coerceImageRiskScore(
  classification: ImageClassification,
  riskScore: number,
): number {
  if (classification === "ai-generated") {
    return Math.max(riskScore, 60);
  }
  if (classification === "authentic") {
    return Math.min(riskScore, 40);
  }
  // uncertain → 40–70 fence-sitting band
  return Math.max(40, Math.min(70, riskScore));
}

const SUMMARIES: Record<ImageClassification, string> = {
  "ai-generated": "This image appears to have been generated by AI.",
  authentic: "This image appears to be authentic.",
  uncertain: "Detection results are inconclusive — treat with caution.",
};

const EXPLANATION_PREFIXES: Record<ImageClassification, string> = {
  "ai-generated": "The image shows strong indicators of AI generation",
  authentic: "No significant signs of AI generation were detected",
  uncertain: "The analysis returned inconclusive results",
};

export function normalizeProviderResponse(
  raw: SightengineRawResponse,
): ImageDebunkResult {
  const aiScore = raw.type.ai_generated; // 0.0–1.0

  // Classify from a single AI probability score
  let classification: ImageClassification;
  if (aiScore >= 0.7) {
    classification = "ai-generated";
  } else if (aiScore >= 0.4) {
    classification = "uncertain";
  } else {
    classification = "authentic";
  }

  const aiPct = Math.round(aiScore * 100);
  const riskScore = aiPct; // before coercion

  // Confidence = certainty of the verdict.
  // Distance from 0.5 (maximum ambiguity), scaled to 0–100:
  //   ai_generated=0.0 → 100% (certain authentic)
  //   ai_generated=0.5 → 0% (perfectly uncertain)
  //   ai_generated=1.0 → 100% (certain AI)
  const confidence = Math.round(Math.abs(aiScore - 0.5) * 200);

  // Flags
  const flags: string[] = [];
  if (aiPct >= 70) {
    flags.push(`AI generation probability: ${aiPct}%`);
  }
  if (confidence < 30) {
    flags.push(`Low detection confidence: ${confidence}%`);
  }
  if (classification === "uncertain") {
    flags.push("Inconclusive result — use with caution");
  }

  // Explanation
  const explanation =
    `${EXPLANATION_PREFIXES[classification]} (AI probability: ${aiPct}%).` +
    ` Detection confidence: ${confidence}%.`;

  const coercedRiskScore = coerceImageRiskScore(classification, riskScore);

  return {
    classification,
    confidence,
    riskScore: coercedRiskScore,
    safe:
      coercedRiskScore < SAFE_RISK_THRESHOLD &&
      !DANGEROUS_IMAGE_CLASSIFICATIONS.has(classification),
    summary: SUMMARIES[classification],
    flags,
    explanation,
    source: "sightengine",
  };
}
